### ISSUE TITLE
Can you help fix why it stops conversion?

### ISSUE THREAD

**Issue by px39n** [yoursamlan/pubsidian#11]
Hi

I have a vault which has a structure like 

File1...
File2...

A.md
B.md
C.md

However, it only convert the A.md B.md C.md and stop doing anything. I checked output it only exists data.json and pages include only A, B, C.html
![image](https://user-images.githubusercontent.com/53490111/180491581-40cf9af8-9781-4356-8a64-785cb3ecaee8.png)

**Comment by yoursamlan** [comment]
Hi, pubsidian is meant to convert .md notes. It actually lists the .md notes of a folder and converts them to Html so that they can be viewed as a webpage. It is not required and thus is not intended to convert any other file format to do so. For example, let's say, it has some .mp4 files in the directory, then it will show them something like [this](https://noobrook.netlify.app/). You don't have to convert that .mp4 file into anything.

**Comment by yoursamlan** [comment]
However, since all file formats are not supported and can't be viewed on the web (like .zip or .doc), I have restricted the program to touch any other extensions other than .md. However, I am experimenting with several other useful formats like .pdf and .mp4 etc, so that it can show those formats directly into your pubsidian. But, as of now, unfortunately, no other formats except .md are supported to host natively. 

Anyway, I am giving you a glimpse of how .pdf files will look if you use pubsidian.

[Click here to see](https://perlib.netlify.app)
Password is 'demo'.

Just reopen this issue, if you want to share any feedback, or if you have any other queries.

Thank you.
