### ISSUE TITLE
[feature request] support folder and directory

### ISSUE THREAD

**Issue by PabloLION** [yoursamlan/pubsidian#5]
I see in the disclaimer that `directory` is not supported.
I think the code is here:
https://github.com/yoursamlan/pubsidian/blob/afba8420dfd80df8579a87f09ca793ec47c4d072/tools/GUI/PubsidianConverter.py#L105-L114

Are you working on this now? Using folder is the main reason I come back to Obsidian from GitHub Wiki. I think I can do this if you are not working on it.

**Comment by yoursamlan** [comment]
Hi, first of all, thank you for the FR and also, sorry for replying late. Actually, I'm a bit busy for the ongoing and upcoming exams. Thus, I couldn't contribute for some time now. Sorry for that.

Coming to your queries, yes, "directory" can be supported and I had planned to implement it earlier (and you have pointed it correctly; changing the path of the 'directory' along with a few tweaks can solve that problem)  but then, someone had suggested me to implement tags and full text search, so, I got distracted from directory, and kept my self involved to solve those issues.

Now, due to my current academic pressure, it is very hard to keep up the development of this hobby project alone (my contribution map says it all). Thus, for the time being, it will be delightful, if you can develop it by yourself. Any effort towards the betterment of this project is highly appreciated and I will try my best to resolve any queries/ doubts regarding this project. Just a humble request, please create a PR after "successful completion", so that future users can be benefited from that.
Last but not least, wishing you all the best and also I'm really sorry for my incapability of development the project at the very moment.

Thank you :)

**Comment by PabloLION** [comment]
It's ok. I started a simpler version this morning on my new repo [Pablion/free-lightweight-obsidian-publisher](https://github.com/Pablion/free-lightweight-obsidian-publisher). I'm still refactoring your python code but it seems that the cnd of githack you hosted is down? Would you mind check that please. 

Also you are welcome to grab my code after I finish it. I think it would be shortcut for you.

**Comment by Pablion** [comment]
Also you are welcome to grab my code after I finish it. I think it would be shortcut for you.

**Comment by yoursamlan** [comment]
Can you please be more specific, because I have run a quickcheck and everything seems to work fine. I don't get any 404 error to any of my hosted cdn.

**Comment by PabloLION** [comment]
hi @yoursamlan. I thought you fixed it. The `js` and `css` file were down for ~1h and then they came back.

**Comment by yoursamlan** [comment]
Probably issues with the CDN server. However, you can download the files from `pubsidian/CDN/` and can run them locally after modifying `index.html`

**Comment by PabloLION** [comment]
Yes I know. I did it 😄 , but the service was back before I finished.
