### ISSUE TITLE
[FR] Publish state based on frontmatter

### ISSUE THREAD

**Issue by Mara-Li** [yoursamlan/pubsidian#6]
Hello!
I was working on YAFPA, a python script to convert page with Jekyll.

My script support admonition (in sort of), wikilinks and mainly use a state in the frontmatter : it convert and publish only page with `share: true`.

It will be cool to have a similar things here. 

(I don't really like my website in YAFPA, and don't know how can I improve the navigation as you do)

Also, do you support wikilinks? Admonition?

**Comment by yoursamlan** [comment]
Hi!
First of all, your project is wayyyy better and practical than mine (apart from its gigantic name😛). Kudos for that 😊.

Now, coming to your queries one by one...

- Yes! my project supports wikilinks. But there's a big caveat. As of now, `[[directory/some_page.md]]` is not supported. But if you have a single directory for all of your obsidian notes, then `wikilinks` works fine *.

- Now, as per the last published build, `admonition ` isn't supported for my project. But I think that `MD-admonition` can easily be converted into `HTML-accordion` after a few tweaks in my script. 😬

- Coming to your last query, and as @pablion already suggested in #4 I have a plan to introduce something like `.gitignore`, that will eventually give its user some sort of flexibility while publishing their webpages.

If you don't mind, I want to suggest something about your website. the font size in your homepage is slightly on the bigger side [I think it's around 30pxish] and is not going well with the smaller icons (e.g., collection, articles, etc.). If possible, use font-size, same or lesser than your main heading (i.e., Owlly House). I think it will look better. 😬😬

Last, but not least, I want to end with some (harsh) truth. Being a Maths student, I have to rely heavily on pen and paper, rather than using obsidian while taking notes. Now, I have tried both `Latex ` (Slow and monotonous) and `Excalidraw ` (Awesome but with some limitations) with obsidian for taking digital notes; but sadly it turns out to be ineffective and time-consuming for me. So, gradually I have lost the urge to create or update something (also, I am a huge procrastinator) for some apps, which I rarely use nowadays 😔 

Anyway, thank you so much for your suggestions, especially for pointing out `admonition`🤗. I will keep that in my mind while working on the next update.😇

Bonne soirée. (Thanks to duolingo 😅)

**Comment by PabloLION** [comment]
hi @Mara-Li. Your name rang a bell to me because I checked [Mara-Li/yet-another-free-publish-alternative](https://github.com/Mara-Li/yet-another-free-publish-alternative) and I didn't use it. 

I'm now hosting with another workflow and it works quite well ([check how](https://note.pablolion.com/tool/noting%20app/)). 

Also I would suggest @yoursamlan to concentrate more on the d3js graphs instead of repeating the work done by [zoni/obsidian-export](https://github.com/zoni/obsidian-export) (also I used pubsidian instead of YAPFA, despite of YAPFA having a very detailed dev log on obsidian forum)

**Comment by Mara-Li** [comment]
Wow! A big work here.
I would prefer, tbh, use a frontmatter than a external file to exclude file, because I think it's more "smooth" between the export and obsidian.

**Comment by PabloLION** [comment]
> Wow! A big work here. I would prefer, tbh, use a frontmatter than a external file to exclude file, because I think it's more "smooth" between the export and obsidian.

I don't know how does obsidian support the front matter, I personally want to keep the markdown more pure.. I think you can maybe test Hexo. It's better than my current solution (MkDocs) but I abandoned it  because of the front matter...

I just tested that obsidian can hide front matter! so nice!
