### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by sustcsugar** [yoursamlan/pubsidian#7]
Hi ! 
I follow the steps in the usage but some problems happened.
Your program seems don't work properly and I don't know the reason. 
It just convert only one .md file.
if it is because of the Chinese characters ? 
![image](https://user-images.githubusercontent.com/39771054/150399596-2432685f-16e9-4d71-8b6d-fd2c14815d3a.png)

**Comment by yoursamlan** [comment]
![image](https://user-images.githubusercontent.com/33586885/150433741-42045cbd-8087-415f-ac9a-30d782ac2a80.png)

Initially, I guess that can be the reason. Unicode can't decode Chinese characters, thus giving an error.
Here is a possible solution on [Stack Overflow](https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character).
If possible, please run the code manually i.e., by double clicking `PubsidianConverter.py` from this [folder](https://github.com/yoursamlan/pubsidian/tree/main/tools/GUI) and paste the error code from the terminal. It will help to debug further.
Thank you.

**Comment by yoursamlan** [comment]
Since, command line is windows default GBK code, all ' Chinese characters' .encode(‘gbk') When the output result is the same as the 'Chinese character' result.

To sum up, str of python is actually a kind of unicode, and python's default code is ascii. When non-ascii is converted to ascii, an error will be reported.
